version: "2"
services:
   node:
      image: "mynodejs:1.0"
      working_dir: /home/node/
      ports:
        - "8080:3000"
      command: "npm start"
   mongo:
      image: "mongo:4.0"
      volumes:
        - ./mongo:/data/db
