version: "2"
services:
   node:
      image: "vanilleeis23/mynodejs:1.0"
      working_dir: /home/node/
      ports:
        - "8080:3000"
      command: "npm start"
      links:
        - mongo
   mongo:
      container_name: mongo
      image: "mongo:4.0"
      ports: 
        -"27017:27017"
      volumes:
        - ./mongo:/data/db
